version: "3.9"
services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_DB: "naujava"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network: