version: "3.9"
services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_DB: "naujava"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - app-network
  application:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    platform: linux/amd64
    networks:
      - app-network
    environment:
      - PG_DB=naujava
      - PG_USER=postgres
      - PG_PASSWORD=postgres

networks:
  app-network: