server:
  port: 8080
cors:
  origin: "*"
  credentials: false
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PG_HOST:localhost}:5432/${PG_DB:naujava}
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:postgres}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: none
  data:
    rest:
      base-path: /rest